# ====================================================
# Main program
bolt_moveit:
  # run mode
  auto_run: true # do not wait to move interactive markers. note: 'autonomous' setting must be 'false'
  benchmark_performance: false
  display_disjoint_sets: false # connected components
  eliminate_dense_disjoint_sets: false
  check_valid_vertices: false # Collision check every vertex in sparse graph and return error if invalid found

  # create sparse graph
  load_spars: true
  create_spars: true
  continue_spars: false # even if a file has been saved, randomly sample for more coverage
  run_problems: true # do plans?
  sweep_spars_maps: true
  sweep_map_start: 1 # Base 1, not 0
  sweep_map_end: 1 # Base 1, not 0

  # mirror graph
  mirror_graph: false # take a single-arm graph and turn into dual-arm graph
  opposite_arm_name: left_arm_minus_one
  both_arms_group_name: both_arms

  # run type
  headless: false
  num_problems: 1
  problem_type: 1 # 0 - random, 1 - imarkers

  # execution
  velocity_scaling_factor: 0.5

  # solver type
  experience_planner: bolt
  #experience_planner: spars2

  # robot setup
  #planning_group_name: right_arm_minus_one
  planning_group_name: both_arms
  arm_jmgs: [right_arm, left_arm]
  ee_tip_links: [right_gripper_tip, left_gripper_tip]

  # other
  use_task_planning: true  # cartesian hybrid planning
  post_processing: false
  post_processing_interval: 20 # how often (in runs) to adjust the graphs
  seed_random: true
  use_logging: false # write to file log info
  collision_checking_enabled: true

  # debugging
  visualize:
    display_database: false # does not display database as it is built, however
    start_goal_states: false
    interpolated_traj: false
    time_between_plans: 2
    database_every_plan: false
  verbose:
    print_trajectory: false
    verbose: false

# ====================================================
sparse_mirror:
  verbose:
    verbose: true

# ====================================================
sparse_generator:
# VAR1
  fourth_criteria_after_failures: 100000 # mode change to 4th criteria after this many failures
  terminate_after_failures: 100000 # total failures, including 4th criteria
# VAR3
  use_discretized_samples: false
  use_random_samples: true
  verify_graph_properties: false
  verbose:
    verbose: true
    guarantees: true # show data about the optimiality guarantees verification

# ====================================================
sparse_criteria:
  #sparse_delta_fraction: 0.4
  sparse_delta_fraction: 0.45
  #sparse_delta_fraction: 0.5
  penetration_overlap_fraction: 0.01
  near_sample_points_multiple: 2 # multiply this times number of dimensions
# VAR4
  stretch_factor: 4 # 0 means auto set
  use_l2_norm: false # instead use L1
  use_connectivy_criteria: true # main feature
  use_quality_criteria: false # 4th criteria
# VAR2
  use_clear_edges_near_vertex: false # Methods to Reduce Outdated/Redundant Edges
# VAR5
  use_direct_connectivity_criteria: true # Add direct edge instead of also vertex
# VAR6
  use_smoothed_path_improvement_rule: true # Improving the Smoothed Quality Path Criteria
# VAR7
  use_edge_improvement_rule: true # Modification of Quality Criteria for $L_1$ Space
  verbose:
    added_reason: false # debug criteria for adding vertices & edges
    criteria: false # all criteria except 4th (quality)
    quality: false # 4th criteria
    quality_max_spanner: false
    remove_close: false
  visualize:
    attempted_states: false # show the current sampled state before its added
    connectivity: false # show states in different connected components for connectivity criteria
    quality_criteria: false # window 5
    quality_criteria_close_reps: false # window 3
    quality_criteria_sampler: false
    quality_criteria_astar: false # show results of astar test
    remove_close_vertices: false

# ====================================================
sparse_graph:
  save_enabled: true
  super_debug: false # run more checks and tests that slow down speed
  obstacle_clearance: 0.0 #0.0035 # max before gripper piece is in collision
  verbose:
    add: false # debug when addVertex() and addEdge() are called
    search: false
  visualize:
    spars_graph: false
    spars_graph_speed: 0.000001 # if 0, does not animate but only single image draw
    database_vertices: true # must have spars_graph enabled
    database_edges: true # must have spars_graph enabled
    database_coverage: false # the grey circles around vertices, must have spars_graph enabled
    projection: false # show the joint space in a nD grid
    graph_after_loading: false # show graph after loading from file (can be slow!)
    quality_path_smoothing: false # simplification
    astar: false # show node expansions and openings
    astar_speed: 0.01 # how many seconds to wait between each visualization
    voronoi_diagram: false
    voronoi_diagram_animated: false

# ====================================================
sparse_smoother:
  visualize:
    quality_path_smoothing: false # show smoothing simplification

# ====================================================
vertex_discretizer:
  verbose:
    verbose: true
    thread: false # output within threading (very verbose)
  visualize:
    grid_generation: false
    grid_generation_wait: false

# ====================================================
candidate_queue:
  verbose:
    verbose: false
    neighbor: false
    clear: false
    queue_full: false
    queue_empty: false
    thread: false

# ====================================================
task_graph:
  num_neighbors_connect_to_cart: 10
  verbose:
    verbose: false
    add: false # debug when addVertex() and addEdge() are called
    search: false
    visualize: false
    heuristic: false
    clear: false
    generate_task: false
  visualize:
    task_graph: false
    task_graph_speed: 0.001 # if 0, does not animate but only single image draw
    database_vertices: true
    database_edges: true
    astar: false # show node expansions and openings
    astar_speed: 0.01 # how many seconds to wait between each visualization

# ====================================================
debug_interface:
  autonomous: false
  full_autonomous: false

# ====================================================
bolt_planner:
  verbose:
    verbose: false
    collision_check: false
  visualize:
    smoothed_trajectory: true
    start_goal: false
    lazy_collision_check: false
    each_solution_step: false

# ====================================================
bolt:
  visualize:
    raw_trajectory: true
    smooth_trajectory: true
    robot_trajectory: true

# ====================================================
cart_path_planner:
  ik_solver:
    discretization: 4 # 0.785 # pi / 4
  trajectory:
    discretization: 0.01 # how much space, in meters, between trajectory points
    timing: 0.3 # time allowed between each Cartesian point, e.g. discretization for velocity
  tolerance:
    pi_fraction_increment: 0.2 # 2xPI / this number = number of steps to divide each dimension by
    roll: 0.314 # pi/10
    pitch: 0.314 # pi/10
    # roll: 0.628 # pi/5
    # pitch: 0.628 # pi/5
    yaw: 0 # pi
  hybrid_rand_factor: 5 # number of times to randomly add the two arm trajectories together
  verbose: false
  visualize:
    all_cart_poses: false # show the markers for each pose location
    all_cart_poses_individual: true # show the markers one by one for each pose location
    all_solutions: false # show each solution along trajectory when moving the interactive markers
    all_solutions_sleep: 0.1 # time between each solution for viewing
    rejected_edges_due_to_timing: false
    combined_solutions: false # show the robot state for each combined pose
    rejected_states: false # show invalid collision checks

# ====================================================
# Interface for publishing joint/cartesian commands to the low level controllers
execution_interface:
  #command_mode: joint_publisher # method for publishing commands from this node to low level controller
  command_mode: joint_execution_manager
  cartesian_command_topic: /baxter/cartesian_controller/cartesian_command # command output from this node
  joint_trajectory_topic: /baxter/cartesian_controller/command # command output from this node
  save_traj_to_file: false # debug mode for creating a CSV for use with Matlab
  save_traj_to_file_path: /home/dave/ros/current/ws_swri/src/trajectory_data/ # debug
  visualize_trajectory_line: true # show in RViz a series of markers visualizing path
  visualize_trajectory_path: true # show in RViz the robot moving on the trajectory path
  check_for_waypoint_jumps: false # ensure that any trajectory that is published does not have huge discontinuties in joint space

# MoveIt Boilerplate Base Functionality
moveit_base:
  joint_state_topic: /robot/joint_states # location to recieve updates of the robot's pose
  joint_model_group: both_arms # the main planning group to control
  planning_scene_topic: /swri/planning_scene  # topic for communicating the collision obj in the env with other nodes
  rviz:
    markers_topic: /baxter/markers
    robot_state_topic: /baxter/robot_state
    trajectory_topic: /baxter/display_trajectory
